name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  date_format: ^1.0.4
  flutter_webview_plugin: ^0.3.4
  flutter_swiper: ^1.1.6
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/timg.jpg
    - assets/banner/b1.jpg
    - assets/banner/b2.jpg
    - assets/banner/b3.jpg
    - assets/banner/b4.jpg
    - assets/images/a1.jpg

  uses-material-design: true

